### ISSUE TITLE
organization of code

### ISSUE THREAD

**Issue by ianfoster** [AD-SDL/rpl_workcell#31]
We should come up with a consistent organization for the material in this directory, and describe that organization (and the contents of the subdirectories) in the README.

- The top-level README.md currently has explanatory documentation written by Ian. That maybe can be moved to the doc that is being created elsewhere, as I understand things.
- The names of the subdirectories bio_workcell, color_picker, pcr_description, pcr_workcell should make clear what they are. Two are "workcells", one is a "description", one is something else? If they are the same sort of thing, let's name them the same. Maybe should be something like subdirectory "color_picker_application"?
- Within the subdirectories, it would be good to have a consistent naming scheme. I assume that each has a Python program that names one or more YAML files? Maybe the Python file should be e.g. color_picker_driver.py?

**Comment by ravescovi** [comment]
>
>    - The top-level README.md currently has explanatory documentation
>    written by Ian. That maybe can be moved to the doc that is being created
>    elsewhere, as I understand things.
>
> This is being moved to a "concepts" page here:
https://rpl-wei.readthedocs.io/en/latest/pages/introduction.html#

>
>    - The names of the subdirectories bio_workcell, color_picker,
>    pcr_description, pcr_workcell should make clear what they are. Two are
>    "workcells", one is a "description", one is something else? If they are the
>    same sort of thing, let's name them the same. Maybe should be something
>    like subdirectory "color_picker_application"?
>
> The description one will move out, it is actually a ros_package that is
used to render the gazebo version of the rpl. It is a ros standard to call
those packages `_description`

>
>    - Within the subdirectories, it would be good to have a consistent
>    naming scheme. I assume that each has a Python program that names one or
>    more YAML files? Maybe the Python file should be e.g.
>    color_picker_driver.py?
>
> Agreed. We are discussing what should be the name of each layer. I like
`application` for the main Python file. I am not sure if `driver` is going
to be more confusing with the hardware drivers?

**Comment by ravescovi** [comment]
Closed due to new versions of the code.
